"use strict";var d=Object.defineProperty;var S=Object.getOwnPropertyDescriptor;var b=Object.getOwnPropertyNames;var F=Object.prototype.hasOwnProperty;var T=(s,t)=>{for(var e in t)d(s,e,{get:t[e],enumerable:!0})},$=(s,t,e,r)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of b(t))!F.call(s,n)&&n!==e&&d(s,n,{get:()=>t[n],enumerable:!(r=S(t,n))||r.enumerable});return s};var k=s=>$(d({},"__esModule",{value:!0}),s);var M={};T(M,{default:()=>g});module.exports=k(M);var i=require("obsidian"),p={rendererEndpoint:"http://127.0.0.1:8765",attachmentFolder:"_link-previews",staleDays:30},y="link-previews:screenshot";function P(s){let t=2166136261;for(let e=0;e<s.length;e++)t=Math.imul(t^s.charCodeAt(e),16777619);return(t>>>0).toString(16).padStart(8,"0")}function x(s){let t=s.match(/https?:\/\/[^\s)>]+/i);return t?t[0].replace(/[.,;]+$/,""):null}function A(s,t,e){return`<!-- ${y}
url=${s}
image=${t}
captured=${e}
-->`}function D(s,t){let e=new RegExp(`<!-- ${y}\\nurl=${t.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}\\nimage=([^\\n]+)`);return s.match(e)?.[1]??null}var g=class extends i.Plugin{async onload(){this.settings=Object.assign({},p,await this.loadData()),this.addSettingTab(new u(this.app,this)),this.addCommand({id:"enrich-url-screenshot",name:"Enrich URL with webpage screenshot",editorCallback:(t,e)=>this.enrich(t,e)}),this.addCommand({id:"refresh-url-screenshot",name:"Refresh URL screenshot",editorCallback:(t,e)=>this.enrich(t,e,!0)}),this.registerMarkdownPostProcessor((t,e)=>this.renderCards(t,e))}async enrich(t,e,r=!1){if(i.Platform.isMobile){new i.Notice("Screenshot generation is available on desktop only.");return}let n=t.getLine(t.getCursor().line),a=x(n);if(!a){new i.Notice("Place the cursor on a line containing an HTTP(S) URL.");return}if(!C(e))return;let h=P(a+"|"+this.settings.rendererEndpoint),o=`${this.settings.attachmentFolder}/${h}.png`;try{let l=await(0,i.requestUrl)({url:`${this.settings.rendererEndpoint.replace(/\/$/,"")}/screenshot`,method:"POST",body:JSON.stringify({url:a}),headers:{"content-type":"application/json"}});if(l.status<200||l.status>=300)throw new Error(`renderer returned ${l.status}`);let m=l.arrayBuffer;await this.app.vault.createFolder(this.settings.attachmentFolder).catch(()=>{});let f=this.app.vault.getAbstractFileByPath(o);f instanceof i.TFile?await this.app.vault.modifyBinary(f,m):await this.app.vault.createBinary(o,m);let v=t.getValue(),E=`![Webpage preview](${o})`,w=A(a,o,new Date().toISOString());v.includes(w)||t.replaceRange(`

${E}
${w}
`,{line:t.getCursor().line+1,ch:0}),new i.Notice(r?"Screenshot refreshed.":"Screenshot saved to vault.")}catch(l){new i.Notice(`Screenshot unavailable: ${l instanceof Error?l.message:"renderer error"}`)}}async renderCards(t,e){let r=Array.from(t.querySelectorAll("a.external-link"));for(let n of r){let a=n.href,c=e.sourcePath?await this.app.vault.read(this.app.vault.getAbstractFileByPath(e.sourcePath)):"",h=D(c,a);if(h&&this.app.vault.getAbstractFileByPath(h)){this.card(n,a,h,void 0);continue}this.fetchOg(a).then(o=>this.card(n,a,void 0,o)).catch(()=>{})}}async fetchOg(t){let r=(await(0,i.requestUrl)({url:t,method:"GET"})).text,n={};for(let a of["title","description","image","site_name"]){let c=r.match(new RegExp(`<meta[^>]+(?:property|name)=["'](?:og:)?${a}["'][^>]+content=["']([^"']+)`,"i"));c&&(n[a]=c[1])}return n.title||=r.match(/<title[^>]*>([^<]+)/i)?.[1]||t,n}card(t,e,r,n){let a=t.parentElement?.createDiv({cls:"link-preview-card"});a&&(a.createEl("a",{text:n?.title||"Webpage preview",href:e,cls:"link-preview-title"}),r?a.createEl("img",{attr:{src:this.app.vault.getResourcePath(this.app.vault.getAbstractFileByPath(r)),alt:"Webpage screenshot"}}):n?.image&&a.createEl("img",{attr:{src:n.image,alt:""}}),n?.description&&a.createEl("p",{text:n.description,cls:"link-preview-description"}))}};function C(s){return s.file}var u=class extends i.PluginSettingTab{constructor(e,r){super(e,r);this.plugin=r}display(){let e=this.containerEl;e.empty(),e.createEl("h2",{text:"Link Previews"}),new i.Setting(e).setName("Screenshot helper endpoint").setDesc("Local HTTP helper; never used on mobile.").addText(r=>r.setValue(this.plugin.settings.rendererEndpoint).onChange(async n=>{this.plugin.settings.rendererEndpoint=n.trim(),await this.plugin.saveData(this.plugin.settings)})),new i.Setting(e).setName("Attachment folder").addText(r=>r.setValue(this.plugin.settings.attachmentFolder).onChange(async n=>{this.plugin.settings.attachmentFolder=n.trim()||p.attachmentFolder,await this.plugin.saveData(this.plugin.settings)})),new i.Setting(e).setName("Stale screenshot age (days)").addText(r=>r.setValue(String(this.plugin.settings.staleDays)).onChange(async n=>{this.plugin.settings.staleDays=Math.max(1,Number(n)||p.staleDays),await this.plugin.saveData(this.plugin.settings)}))}};
